# Generated by Django 2.2.6 on 2019-10-22 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit_app', '0010_auto_20191023_0224'),
        ('recruit_polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='recruit',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='recruit_app.Recruit'),
        ),
    ]
