# Generated by Django 2.2.6 on 2019-10-23 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit_polls', '0002_answer_recruit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='recruit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruit_app.Recruit'),
        ),
    ]
