# Generated by Django 2.2.6 on 2019-10-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit_polls', '0004_auto_20191023_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(choices=[(True, 'Да'), (False, 'Нет')], default=True, max_length=32, verbose_name='Ответ'),
        ),
    ]
