# Generated by Django 2.2.6 on 2019-10-20 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit_app', '0003_recruit_is_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='SithName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя Ситха')),
            ],
        ),
        migrations.AlterField(
            model_name='sith',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit_app.SithName', verbose_name='Имя Ситха'),
        ),
    ]
