# Generated by Django 2.2.6 on 2019-10-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit_app', '0004_auto_20191020_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sithname',
            name='name',
        ),
        migrations.AddField(
            model_name='sithname',
            name='sith_name',
            field=models.CharField(max_length=64, null=True, verbose_name='Имя Ситха'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Планета'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Имя Рекрута'),
        ),
    ]
