# Generated by Django 2.2.6 on 2019-10-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit_app', '0010_auto_20191023_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
